Django_Practice_CRUD_App/My_First_Project/My_First_Project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/',admin.site.urls),
    path('',include('first_app.urls')),
    ]

Django_Practice_CRUD_App/My_First_Project/first_app/urls.py
from django.conf.urls import include
from django.urls import path
from first_app import views



app_name="first_app"

urlpatterns=[

path('',views.index,name='index'),
path('album_form/',views.album_form,name='album_form'),
path('musician_form/',views.musician_form,name='musician_form'),
path('album_list/<int:artist_id>/',views.album_list,name='album_list'),
path('edit_artist/<int:artist_id>/',views.edit_artist,name='edit_artist'),
path('edit_album/<int:album_id>/',views.edit_album,name='edit_album'),
path('delete_album/<int:album_id>/',views.delete_album,name='delete_album'),
path('delete_artist/<int:artist_id>/',views.delete_musician,name='delete_artist'),
]

Django_Practice_CRUD_App/My_First_Project/templates/first_app/django3/portfolio/employee/urls.py

from django.urls import path,include
from . import views

urlpatterns = [

    path('new/',views.employee),
    path('profile/',views.profile),


]

Django_Practice_CRUD_App/My_First_Project/templates/first_app/django3/portfolio/templets/portfolio/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home),
    path('about/',views.about),
    path('contactus/',views.contact),
    path('employee/',include('employee.urls')),

]

Django_Practice_CRUD_App/My_First_Project/first_app/models.py
from django.db import models

# Create your models here.
class Musician(models.Model):
    #id=models.AutoField(Primary_Key=True)  hidden by default we dont have to write
    first_name=models.CharField(max_length=50)
    last_name=models.CharField(max_length=50)
    instrument=models.CharField(max_length=100)

    def __str__(self):
        return self.first_name + " " + self.last_name




class Album(models.Model):
        #id=models.AutoField(Primary_Key=True)  hidden by default we dont have to write
        artist=models.ForeignKey(Musician,on_delete=models.CASCADE)
        name=models.CharField(max_length=50)
        release_date=models.DateField()


        rating=(
        (1,'WORST'),
        (2,'BAD'),
        (3,'NOT BAD'),
        (4,'GOOD'),
        (5,'EXCELLENT'),
        )

        num_stars=models.IntegerField(choices=rating)

#        class Meta: {for chnage the table name}
#            db_table='album'



        def __str__(self):
            return self.name + ", Rating " + str(self.num_stars)

Django_Practice_CRUD_App/My_First_Project/templates/first_app/django3/portfolio/employee/models.py
from django.db import models

# Create your models here.

Django_Practice_CRUD_App/My_First_Project/first_app/forms.py
from django import forms
#from django.core import validators
from first_app import models

class MusicianForm(forms.ModelForm):
    class Meta:
        model=models.Musician
        fields="__all__"

class AlbumForm(forms.ModelForm):
    release_date=forms.DateField(widget=forms.TextInput(attrs={'type':'date'}))
    class Meta:
        model=models.Album
        fields="__all__"

Django_Practice_CRUD_App/My_First_Project/first_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from first_app.models import Musician,Album
from first_app import forms
from django.db.models import Avg

def index(request):
    musician_list=Musician.objects.order_by('first_name')
    diction={'title':'Home Page !!',"musician_list":musician_list}
    return render(request,'first_app/index.html',context=diction)


def album_list(request,artist_id):
    artist_info=Musician.objects.get(pk=artist_id)
    albume_list=Album.objects.filter(artist=artist_id)
    artist_rating=Album.objects.filter(artist=artist_id).aggregated(Avg('num_stars'))
    diction={'title':'List Of Albums !!','artist_info':artist_info,'album_list':artist_id}
    return render(request,'first_app/album_list.html',context=diction)

def musician_form(request):
    form=forms.MusicianForm()

    if request.method=='POST':
        form=forms.MusicianForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return index(request)

    diction={'title':'Add Musician !!','musician_form':form}
    return render(request,'first_app/musician_form.html',context=diction)

def album_form(request):

    #musician_list=Musician.objects.order_by('first_name')
    form=forms.AlbumForm()

    if request.method=='POST':
        form=forms.AlbumForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return index(request)

    diction={'title':'Add Album !!','album_form':form}
    return render(request,'first_app/album_form.html',context=diction)

def edit_artist(request,artist_id):
    artist_info=Musician.objects.get(pk=artist_id)
    form=forms.MusicianForm(instance=artist_info)
    diction={}

    if request.method=='POST':
        form=forms.MusicianForm(request.POST,instance=artist_info)
        if form.is_valid():
            form.save(commit=True)
            return album_list(request,artist_id)
            diction.update({'success_text1':'Artist Sucessfully Updated '})

    diction.update({'edit_form':form})
    return render(request,'first_app/edit_artist.html',context=diction)

def edit_album(request,album_id):
    albume_info=Album.objects.get(pk=album_id)
    form=forms.AlbumForm(instance=album_info)
    diction={}

    if request.method=='POST':
        form=forms.AlbumForm(request.POST,instance=album_info)
        if form.is_valid():
            form.save(commit=True)
            diction.update({'success_text':'Album Sucessfully Updated '})


    diction.update({'edit_form':form})
    diction.update({'album_id':album_id})
    return render(request,'first_app/edit_album.html',context=diction)

def delete_album(request,album_id):
    album=Album.objects.get(pk=album_id).delete()
    diction={'delete_success':'album delete successfully'}
    return render(request,'first_app/delete.html',context=diction)

def delete_musician(request,artist_id):
    artist=Musician.objects.get(pk=artist_id).delete()
    diction={'delete_success':'musician delete successfully'}
    return render(request,'first_app/delete.html',context=diction)

Django_Practice_CRUD_App/My_First_Project/templates/first_app/django3/portfolio/employee/views.py
from django.shortcuts import render
from django.http import HttpResponse

def employee(request):
    return HttpResponse('This is the employee page')


def profile(request):
    return render(request,'employee/profile.html')

# Create your views here.

Django_Practice_CRUD_App/My_First_Project/templates/first_app/django3/portfolio/templets/portfolio/views.py
from django.shortcuts import render
from django.http import HttpResponse


def home(request):
    return render(request,'index.html')

def about(request):
    data='get all data from the database'
    return HttpResponse(data)

def contact(request):
    return HttpResponse('This is our Contact page')

Django_Practice_CRUD_App/My_First_Project/templates/first_app/album_form.html
<!DOCTYPE html>
{% extends "first_app/base.html" %}
{% block body_block %}
<h1>Album Form </h1>
<form  method="POST">
  {{ album_form.as_p }}
  {% csrf_token %}
  <input type="submit" name="submit" value="Add Album" class="btn btn-primary btn -sm ">
</form>
{% endblock %}

Django_Practice_CRUD_App/My_First_Project/templates/first_app/album_list.html
<!DOCTYPE html>
{% extends "first_app/base.html" %}
{% block body_block %}
<h1> list of Album </h1>
<h4> Artist_name : {{ artist_info.first_name }}  {{ artist_info.last_name }} </h4>
<h4> Instrument_name : {{ artist_info.instrument }} </h4>
<h4>Artist Rating :{{ artist_rating.num_stars__avg }} </h4>
<hr>
<a href="{% url 'first_app:edit_artist' artist_id=artist_info.id %}" class="btn btn-primary btn-sm">Edit</a>

<table class="table-bordered">
  <tr>
    <th>Album Name</th>
    <th>Release date</th>
    <th>Rating</th>
  </tr>
  {% for album in album_list %}
  <tr>
    <td> <a href="{% url 'first_app:edit_albume' album_id=album.id %}">{{ album.name }}</a> </td>
    <td>{{ album.release_date }}</td>
    <td>{{ album.num_stars }}</td>
  </tr>
  {% endfor %}
</table>
<br>
<a href="{% url 'first_app: delete_artist' artist_id=artist_info.id %}" onclick="return confirm('delete Musician?')" class="btn btn-danger btn-sm">Delete</a>

{% endblock %}

Django_Practice_CRUD_App/My_First_Project/templates/first_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>{{ title }}</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-dark">
      <div class="navbar-nav">
        <a class="nav-item nav-link active" href="{% url 'first_app:index' %}">Home</a>
        <a class="nav-item nav-link" href="{% url 'first_app:musician_form' %}">Add Musician</a>
        <a class="nav-item nav-link" href="{% url 'first_app:album_form' %}">Add Album</a>
      </div>
    
   </nav>

   <div class="container">

     {% block body_block %}

     {% endblock %}
   </div>


  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

Django_Practice_CRUD_App/My_First_Project/templates/first_app/delete.html
{% extends "first_app/base.html" %}
{% block body_block %}
<h3>Delete Page</h3>

<div class="alert alert-success">{{ delete_success }}
</div>

{% endblock %}

Django_Practice_CRUD_App/My_First_Project/templates/first_app/django3/portfolio/templets/employee/profile.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>profile page</title>
  </head>
  <body>
    <h1>This is our profile page </h1>
    <strong>Name=Andr</strong>
    <strong>Email=xyz@gmail.com</strong>
  </body>
</html>

Django_Practice_CRUD_App/My_First_Project/templates/first_app/django3/portfolio/templets/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>profile page</title>
  </head>
  <body>
    <h1>This is our home page </h1>

  </body>
</html>

Django_Practice_CRUD_App/My_First_Project/templates/first_app/edit_album.html
{% extends "first_app/base.html" %}
{% block body_block %}
<h3>Edit Albume</h3>

{% if success_text %}
<div class="alert alert-success">{{ success_text }}
</div>
{% endif %}

<form  method="POST">
  {{ edit_form.as_p }}
  {% csrf_tokan  %}
  <input type="submit" name="submit" value="Update"  class="btn btn-primary btn-sm" >
</form>
<br>
<a href="{% url 'first_app:delete_album' album_id=album_id %}" class='btn btn-danger btn-sm' onclick="return confirm('Delete this album ?') ">Delete</a>
{% endblock %}

Django_Practice_CRUD_App/My_First_Project/templates/first_app/edit_artist.html
{% extends "first_app/base.html" %}
{% block body_block %}
<h3>Edit Artist</h3>

{% if success_text1 %}
<div class="alert alert-success">{{ success_text1 }}
</div>
{% endif %}

<form  method="POST">
  {{ edit_form.as_p }}
  {% csrf_tokan  %}
  <input type="submit" name="submit" value="Update"  class="btn btn-primary btn-sm" >
</form>

{% endblock %}

Django_Practice_CRUD_App/My_First_Project/templates/first_app/index.html
<!DOCTYPE html>
{% extends "first_app/base.html" %}
{% block body_block %}
<h1>List Of Musician</h1>


<ul>
 {% if musician_list %}

{% for Musician in musician_list %}

<li><a href="{% url 'first_app:album_list' artist_id=musician.id %}">{{musician.first_name}} {{musician.last_name}}</a></li>


{% endfor %}
{% else %}
<h3> no musician in the list </h3>
{% endif %}
</ul>


{% endblock %}

Django_Practice_CRUD_App/My_First_Project/templates/first_app/musician_form.html
<!DOCTYPE html>
{% extends "first_app/base.html" %}
{% block body_block %}
<h1>Musician Form</h1>
<form  method="POST">
  {{ musician_form.as_p }}
  {% csrf_token %}
  <input type="submit" name="submit" value="Add Musician" class="btn btn-primary btn -sm ">
</form>
{% endblock %}